steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: "Install dependencies"
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/npm'
    id: "Run unit tests"
    args: [ 'run', 'test:unit' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: "Build the container image"
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: "Push the image to Container Registry"
    args: ['push', 'gcr.io/$PROJECT_ID/frontend']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: "Deploy image to Cloud Run"
    args: ['beta', 'run', 'deploy', 'frontend-demo', '--image', 'gcr.io/$PROJECT_ID/frontend', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - gcr.io/$PROJECT_ID/frontend
